CREATE DATABASE CENTER;
USE CENTER;

CREATE TABLE WEEK_PLANS
(
    ID         VARCHAR(36) NOT NULL COMMENT 'WEEK PLAN PRIMARY ID',
    WEEK_NUM   INT COMMENT 'WEEK NUM',
    CONTENT    VARCHAR(9999) COMMENT 'CONTENT',
    AWARD      VARCHAR(999) COMMENT 'AWARD',
    PUNISHMENT VARCHAR(999) COMMENT 'PUNISHMENT',
    PRIMARY KEY (ID)
);